import type { LucideIcon } from "lucide-react"

export interface NavItem {
  title: string;
  href: string;
  disabled?: boolean;
  external?: boolean;
  icon?: LucideIcon;
  label?: string;
  description?: string;
}

export interface TestCase {
  input: string;
  expectedOutput: string;
}

export interface Challenge {
  id: string;
  title: string;
  description: string;
  language: string; // e.g., "JavaScript", "Python"
  difficulty: 'Easy' | 'Medium' | 'Hard';
  points: number; // Points for correct prediction
  deadline: string; // ISO date string
  status: 'open' | 'closed' | 'assessing' | 'completed';
  testCases?: TestCase[]; // Provided by admin or generated by AI
  exampleSolution?: string; // An example of code that might be tested
  imageUrl?: string; // Optional image for the challenge
  aiHint?: string; // data-ai-hint for image
}

export interface User {
  id: string;
  name: string;
  avatarUrl?: string;
  aiHintAvatar?: string;
  score: number;
}

export interface Prediction {
  id: string;
  userId: string;
  challengeId: string;
  submittedCode: string;
  predictedOutcome: { // User's prediction
    willPass: boolean;
  };
  actualOutcome?: { // Result from AI assessment
    willPass: boolean;
    reasoning?: string;
  };
  isCorrect?: boolean;
  pointsEarned: number;
  submissionDate: string; // ISO date string
}

export interface ProposedBet {
  id: string;
  challengeId: string;
  proposingUserId: string; // User who is making the bet (Proposer)
  targetUserId: string;    // User whose prediction is the subject of the bet (Target)
  targetPredictionId: string; // The ID of the Target's prediction
  betAmount: number;
  // The Proposer is betting that the Target's prediction will be INCORRECT.
  // e.g., If Target predicted PASS, Proposer bets actual outcome will be FAIL.
  status: 'pending_acceptance' | 'accepted' | 'declined' | 'resolved' | 'cancelled';
  winnerId?: string; // proposingUserId or targetUserId
  createdAt: string; // ISO date string
  resolvedAt?: string; // ISO date string
}
