import type { LucideIcon } from "lucide-react"

export interface NavItem {
  title: string;
  href: string;
  disabled?: boolean;
  external?: boolean;
  icon?: LucideIcon;
  label?: string;
  description?: string;
}

export interface TestCase {
  input: string;
  expectedOutput: string;
}

export interface Challenge {
  id: string;
  title: string;
  description: string;
  language: string; // e.g., "JavaScript", "Python"
  difficulty: 'Easy' | 'Medium' | 'Hard';
  points: number; // Points for correct prediction
  deadline: string; // ISO date string
  status: 'open' | 'closed' | 'assessing' | 'completed';
  testCases?: TestCase[]; // Provided by admin or generated by AI
  exampleSolution?: string; // An example of code that might be tested
  imageUrl?: string; // Optional image for the challenge
  aiHint?: string; // data-ai-hint for image
}

export interface User {
  id: string;
  name: string;
  avatarUrl?: string;
  aiHintAvatar?: string;
  score: number;
}

export interface Prediction {
  id: string;
  userId: string;
  challengeId: string;
  submittedCode: string;
  predictedOutcome: { // User's prediction
    willPass: boolean;
  };
  actualOutcome?: { // Result from AI assessment
    willPass: boolean;
    reasoning?: string;
  };
  isCorrect?: boolean;
  pointsEarned: number;
  submissionDate: string; // ISO date string
}
